name: "CI: Check Code Formatting"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Code Formatting
      run: |
        sudo apt update
        sudo apt install mm-common clang-format-8
        alias clang-format="clang-format-8"
        ./autogen.sh --enable-warnings=fatal
        make check-format
